name: Publish

on: push
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - run: mvn -B package --file pom.xml
    - run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
    # - uses: actions/setup-java@v2
    #   with:
    #     distribution: 'temurin'
    #     java-version: '8'
    #     cache: 'maven'
    #     server-id: ossrh
    #     server-username: MAVEN_USERNAME
    #     server-password: MAVEN_CENTRAL_TOKEN
    #     gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
    #     gpg-passphrase: MAVEN_GPG_PASSPHRASE
    # - run: mvn deploy
    #   env:
    #     MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
    #     MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
    #     MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
